### ISSUE TITLE
Icon animation only plays once

### ISSUE THREAD

**Issue by searchy2** [javiersantos/MaterialStyledDialogs#29]
In the first build of Material Styled Dialogs, the icon animation would play every time the dialogue appears. Now, the icon animation only plays the first time the dialogue appears. 

EDIT: I've looked a bit further and the cause appears to be update v1.1.1 
In that update, the dialogue is not rebuilt everytime show() is called which means the animation would not play again. Is there a way around this?

**Comment by javiersantos** [comment]
I've just released the 2.0 update with some major changes (please see the [release description](https://github.com/javiersantos/MaterialStyledDialogs/releases/tag/2.0)).

There is a workaround using the latest version in order to plays the animation every time the dialog is displayed:

```Java
MaterialStyledDialog.Builder dialog = new MaterialStyledDialog.Builder(this)
    .setTitle("Awesome!")
    .setDescription("What can we improve? Your feedback is always welcome.")
    ...
    // Add other customizations, BUT don't use .build() or .show() here.
```

Then use `dialog.show` to display the dialog.
